import Head from 'next/head'
import HomePage from './home'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Top Nhà Cái</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  )
}
