import React from "react";
import PropTypes from "prop-types";
import Image from "next/image";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCheck, faMinus, faPlus
} from "@fortawesome/free-solid-svg-icons";
import { fab } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
library.add(
  fab,
  faCheck,
  faMinus,
  faPlus
);

function CompareBets(props) {
  return (
    <article id="ctwidget_ssnc-5" className="widget widget_ctwidget_ssnc">
      <div className="vbcompare_nhacai ">
        <div className="bxinner">
          <div className="title bxwidget_title">
            <span>new</span>
            <a href="https://vaobo.com/so-sanh-nha-cai/" rel="dofollow">
              So sánh nhà cái
            </a>
          </div>
          <form action="https://vaobo.com/so-sanh-nha-cai/" method="GET">
            <label>Vui lòng chọn danh sách nhà cái bên dưới</label>
            <div className="bxallfield">
              <div className="field_item">
                <div
                  id="bxsl_img_nc1"
                  data_name="nc1"
                  className="bxcs_select_img"
                >
                  <div className="bxshow_dropdown">
                    <button className="bximg_selected">
                      <span>
                        <Image
                          src="https://vaobo.com/wp-content/uploads/2021/08/W88.png?v=1655975657"
                          width="89"
                          height="28"
                          alt="w88"
                        />
                      </span>
                    </button>
                    <ul className="bximgdropdown" style={{ display: "none" }}>
                      <li data-id="171" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/W88.png?v=1655975657"
                            width="89"
                            height="28"
                            alt="w88"
                          />
                        </span>
                      </li>
                      <li
                        data-id="170"
                        data-index="nc1"
                        style={{ display: "none" }}
                      >
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/FB88.png?v=1655975658"
                            width="89"
                            height="23"
                            alt="fb88"
                          />
                        </span>
                      </li>
                      <li data-id="167" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/M88.png?v=1655975658"
                            width="60"
                            height="26"
                            alt="m88-2"
                          />
                        </span>
                      </li>
                      <li data-id="169" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/188BET.png?v=1655975658"
                            width="58"
                            height="38"
                            alt="188bet-2"
                          />
                        </span>
                      </li>
                      <li data-id="168" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/fun88.png?v=1655975658"
                            width="92"
                            height="21"
                            alt="fun88"
                          />
                        </span>
                      </li>
                      <li data-id="165" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/v0bet.png?v=1655975658"
                            width="89"
                            height="36"
                            alt="v0bet"
                          />
                        </span>
                      </li>
                      <li data-id="166" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/letou-2.png?v=1655975658"
                            width="89"
                            height="18"
                            alt="letou-3"
                          />
                        </span>
                      </li>
                      <li data-id="561" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/logo-bet365.png?v=1655975658"
                            width="150"
                            height="57"
                            alt="logo-bet365"
                          />
                        </span>
                      </li>
                      <li data-id="555" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/empire777.png?v=1655975658"
                            width="92"
                            height="13"
                            alt="empire777"
                          />
                        </span>
                      </li>
                      <li data-id="144" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/happyluke-1.png?v=1655975658"
                            width="59"
                            height="34"
                            alt="happyluke-2"
                          />
                        </span>
                      </li>
                      <li data-id="231" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/Loto188-1.png?v=1655975658"
                            width="88"
                            height="29"
                            alt="loto188-2"
                          />
                        </span>
                      </li>
                      <li data-id="559" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/1xbet-logo-png.png?v=1655975658"
                            width="150"
                            height="44"
                            alt="1xbet-logo-png"
                          />
                        </span>
                      </li>
                      <li data-id="557" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/dubaicasino.png?v=1655975658"
                            width="90"
                            height="25"
                            alt="dubaicasino"
                          />
                        </span>
                      </li>
                      <li data-id="520" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/BK8-1.png?v=1655975658"
                            width="62"
                            height="31"
                            alt="bk8-2"
                          />
                        </span>
                      </li>
                      <li data-id="562" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/Oppa888.png?v=1655975658"
                            width="90"
                            height="13"
                            alt="oppa888"
                          />
                        </span>
                      </li>
                      <li data-id="560" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/Vwin.png?v=1655975658"
                            width="64"
                            height="22"
                            alt="vwin"
                          />
                        </span>
                      </li>
                      <li data-id="558" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/logo-nextbet.png?v=1655975658"
                            width="150"
                            height="57"
                            alt="logo-nextbet"
                          />
                        </span>
                      </li>
                      <li data-id="234" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/dafabet.png?v=1655975658"
                            width="93"
                            height="22"
                            alt="dafabet"
                          />
                        </span>
                      </li>
                      <li data-id="229" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/kb.png?v=1655975658"
                            width="83"
                            height="31"
                            alt="kb"
                          />
                        </span>
                      </li>
                      <li data-id="230" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/jbo.png?v=1655975658"
                            width="83"
                            height="42"
                            alt="jbo"
                          />
                        </span>
                      </li>
                      <li data-id="226" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/lixi88.png?v=1655975658"
                            width="90"
                            height="22"
                            alt="lixi88"
                          />
                        </span>
                      </li>
                      <li data-id="233" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/cmd368.png?v=1655975658"
                            width="94"
                            height="18"
                            alt="cmd368"
                          />
                        </span>
                      </li>
                      <li data-id="227" data-index="nc1">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/casio.png?v=1655975658"
                            width="98"
                            height="37"
                            alt="casio"
                          />
                        </span>
                      </li>
                    </ul>
                  </div>
                  <select
                    className="bxselectdf"
                    name="nc1"
                    data-index="nc1"
                    style={{ display: "none" }}
                  >
                    <option
                      value="171"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/W88.png?v=1655975657"
                      data-width="89"
                      data-height="28"
                      
                    >
                      w88
                    </option>
                    <option
                      value="170"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/FB88.png?v=1655975658"
                      data-width="89"
                      data-height="23"
                    >
                      fb88
                    </option>
                    <option
                      value="167"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/M88.png?v=1655975658"
                      data-width="60"
                      data-height="26"
                    >
                      m88-2
                    </option>
                    <option
                      value="169"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/188BET.png?v=1655975658"
                      data-width="58"
                      data-height="38"
                    >
                      188bet-2
                    </option>
                    <option
                      value="168"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/fun88.png?v=1655975658"
                      data-width="92"
                      data-height="21"
                    >
                      fun88
                    </option>
                    <option
                      value="165"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/v0bet.png?v=1655975658"
                      data-width="89"
                      data-height="36"
                    >
                      v0bet
                    </option>
                    <option
                      value="166"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/letou-2.png?v=1655975658"
                      data-width="89"
                      data-height="18"
                    >
                      letou-3
                    </option>
                    <option
                      value="561"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/logo-bet365.png?v=1655975658"
                      data-width="150"
                      data-height="57"
                    >
                      logo-bet365
                    </option>
                    <option
                      value="555"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/empire777.png?v=1655975658"
                      data-width="92"
                      data-height="13"
                    >
                      empire777
                    </option>
                    <option
                      value="144"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/happyluke-1.png?v=1655975658"
                      data-width="59"
                      data-height="34"
                    >
                      happyluke-2
                    </option>
                    <option
                      value="231"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/Loto188-1.png?v=1655975658"
                      data-width="88"
                      data-height="29"
                    >
                      loto188-2
                    </option>
                    <option
                      value="559"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/1xbet-logo-png.png?v=1655975658"
                      data-width="150"
                      data-height="44"
                    >
                      1xbet-logo-png
                    </option>
                    <option
                      value="557"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/dubaicasino.png?v=1655975658"
                      data-width="90"
                      data-height="25"
                    >
                      dubaicasino
                    </option>
                    <option
                      value="520"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/BK8-1.png?v=1655975658"
                      data-width="62"
                      data-height="31"
                    >
                      bk8-2
                    </option>
                    <option
                      value="562"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/Oppa888.png?v=1655975658"
                      data-width="90"
                      data-height="13"
                    >
                      oppa888
                    </option>
                    <option
                      value="560"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/Vwin.png?v=1655975658"
                      data-width="64"
                      data-height="22"
                    >
                      vwin
                    </option>
                    <option
                      value="558"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/logo-nextbet.png?v=1655975658"
                      data-width="150"
                      data-height="57"
                    >
                      logo-nextbet
                    </option>
                    <option
                      value="234"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/dafabet.png?v=1655975658"
                      data-width="93"
                      data-height="22"
                    >
                      dafabet
                    </option>
                    <option
                      value="229"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/kb.png?v=1655975658"
                      data-width="83"
                      data-height="31"
                    >
                      kb
                    </option>
                    <option
                      value="230"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/jbo.png?v=1655975658"
                      data-width="83"
                      data-height="42"
                    >
                      jbo
                    </option>
                    <option
                      value="226"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/lixi88.png?v=1655975658"
                      data-width="90"
                      data-height="22"
                    >
                      lixi88
                    </option>
                    <option
                      value="233"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/cmd368.png?v=1655975658"
                      data-width="94"
                      data-height="18"
                    >
                      cmd368
                    </option>
                    <option
                      value="227"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/casio.png?v=1655975658"
                      data-width="98"
                      data-height="37"
                    >
                      casio
                    </option>
                  </select>
                </div>
              </div>
              <div className="iconcompare">
                <span>
                  <Image
                    data-lazyloaded="1"
                    src="https://vaobo.com/wp-content/themes/salient-child/t-inc/images/icon-compare.png"
                    data-src="https://vaobo.com/wp-content/themes/salient-child/t-inc/images/icon-compare.png"
                    width="15"
                    height="14"
                    alt="icon-compare"
                  />
                </span>
              </div>
              <div className="field_item">
                <div
                  id="bxsl_img_nc2"
                  data_name="nc2"
                  className="bxcs_select_img"
                >
                  <div className="bxshow_dropdown">
                    <button className="bximg_selected">
                      <span>
                        <Image
                          src="https://vaobo.com/wp-content/uploads/2021/08/FB88.png?v=1655975658"
                          width="89"
                          height="23"
                          alt="fb88"
                        />
                      </span>
                    </button>
                    <ul className="bximgdropdown" style={{ display: "none" }}>
                      <li
                        data-id="171"
                        data-index="nc2"
                        style={{ display: "none" }}
                      >
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/W88.png?v=1655975657"
                            width="89"
                            height="28"
                            alt="w88"
                          />
                        </span>
                      </li>
                      <li data-id="170" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/FB88.png?v=1655975658"
                            width="89"
                            height="23"
                            alt="fb88"
                          />
                        </span>
                      </li>
                      <li data-id="167" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/M88.png?v=1655975658"
                            width="60"
                            height="26"
                            alt="m88-2"
                          />
                        </span>
                      </li>
                      <li data-id="169" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/188BET.png?v=1655975658"
                            width="58"
                            height="38"
                            alt="188bet-2"
                          />
                        </span>
                      </li>
                      <li data-id="168" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/fun88.png?v=1655975658"
                            width="92"
                            height="21"
                            alt="fun88"
                          />
                        </span>
                      </li>
                      <li data-id="165" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/v0bet.png?v=1655975658"
                            width="89"
                            height="36"
                            alt="v0bet"
                          />
                        </span>
                      </li>
                      <li data-id="166" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/letou-2.png?v=1655975658"
                            width="89"
                            height="18"
                            alt="letou-3"
                          />
                        </span>
                      </li>
                      <li data-id="561" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/logo-bet365.png?v=1655975658"
                            width="150"
                            height="57"
                            alt="logo-bet365"
                          />
                        </span>
                      </li>
                      <li data-id="555" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/empire777.png?v=1655975658"
                            width="92"
                            height="13"
                            alt="empire777"
                          />
                        </span>
                      </li>
                      <li data-id="144" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/happyluke-1.png?v=1655975658"
                            width="59"
                            height="34"
                            alt="happyluke-2"
                          />
                        </span>
                      </li>
                      <li data-id="231" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/Loto188-1.png?v=1655975658"
                            width="88"
                            height="29"
                            alt="loto188-2"
                          />
                        </span>
                      </li>
                      <li data-id="559" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/1xbet-logo-png.png?v=1655975658"
                            width="150"
                            height="44"
                            alt="1xbet-logo-png"
                          />
                        </span>
                      </li>
                      <li data-id="557" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/dubaicasino.png?v=1655975658"
                            width="90"
                            height="25"
                            alt="dubaicasino"
                          />
                        </span>
                      </li>
                      <li data-id="520" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/BK8-1.png?v=1655975658"
                            width="62"
                            height="31"
                            alt="bk8-2"
                          />
                        </span>
                      </li>
                      <li data-id="562" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/Oppa888.png?v=1655975658"
                            width="90"
                            height="13"
                            alt="oppa888"
                          />
                        </span>
                      </li>
                      <li data-id="560" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/Vwin.png?v=1655975658"
                            width="64"
                            height="22"
                            alt="vwin"
                          />
                        </span>
                      </li>
                      <li data-id="558" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/logo-nextbet.png?v=1655975658"
                            width="150"
                            height="57"
                            alt="logo-nextbet"
                          />
                        </span>
                      </li>
                      <li data-id="234" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/dafabet.png?v=1655975658"
                            width="93"
                            height="22"
                            alt="dafabet"
                          />
                        </span>
                      </li>
                      <li data-id="229" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/kb.png?v=1655975658"
                            width="83"
                            height="31"
                            alt="kb"
                          />
                        </span>
                      </li>
                      <li data-id="230" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/jbo.png?v=1655975658"
                            width="83"
                            height="42"
                            alt="jbo"
                          />
                        </span>
                      </li>
                      <li data-id="226" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/lixi88.png?v=1655975658"
                            width="90"
                            height="22"
                            alt="lixi88"
                          />
                        </span>
                      </li>
                      <li data-id="233" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/cmd368.png?v=1655975658"
                            width="94"
                            height="18"
                            alt="cmd368"
                          />
                        </span>
                      </li>
                      <li data-id="227" data-index="nc2">
                        <span>
                          <Image
                            src="https://vaobo.com/wp-content/uploads/2021/08/casio.png?v=1655975658"
                            width="98"
                            height="37"
                            alt="casio"
                          />
                        </span>
                      </li>
                    </ul>
                  </div>
                  <select
                    className="bxselectdf"
                    name="nc2"
                    data-index="nc2"
                    style={{ display: "none" }}
                  >
                    <option
                      value="171"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/W88.png?v=1655975657"
                      data-width="89"
                      data-height="28"
                    >
                      w88
                    </option>
                    <option
                      value="170"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/FB88.png?v=1655975658"
                      data-width="89"
                      data-height="23"
                    >
                      fb88
                    </option>
                    <option
                      value="167"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/M88.png?v=1655975658"
                      data-width="60"
                      data-height="26"
                    >
                      m88-2
                    </option>
                    <option
                      value="169"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/188BET.png?v=1655975658"
                      data-width="58"
                      data-height="38"
                    >
                      188bet-2
                    </option>
                    <option
                      value="168"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/fun88.png?v=1655975658"
                      data-width="92"
                      data-height="21"
                    >
                      fun88
                    </option>
                    <option
                      value="165"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/v0bet.png?v=1655975658"
                      data-width="89"
                      data-height="36"
                    >
                      v0bet
                    </option>
                    <option
                      value="166"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/letou-2.png?v=1655975658"
                      data-width="89"
                      data-height="18"
                    >
                      letou-3
                    </option>
                    <option
                      value="561"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/logo-bet365.png?v=1655975658"
                      data-width="150"
                      data-height="57"
                    >
                      logo-bet365
                    </option>
                    <option
                      value="555"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/empire777.png?v=1655975658"
                      data-width="92"
                      data-height="13"
                    >
                      empire777
                    </option>
                    <option
                      value="144"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/happyluke-1.png?v=1655975658"
                      data-width="59"
                      data-height="34"
                    >
                      happyluke-2
                    </option>
                    <option
                      value="231"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/Loto188-1.png?v=1655975658"
                      data-width="88"
                      data-height="29"
                    >
                      loto188-2
                    </option>
                    <option
                      value="559"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/1xbet-logo-png.png?v=1655975658"
                      data-width="150"
                      data-height="44"
                    >
                      1xbet-logo-png
                    </option>
                    <option
                      value="557"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/dubaicasino.png?v=1655975658"
                      data-width="90"
                      data-height="25"
                    >
                      dubaicasino
                    </option>
                    <option
                      value="520"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/BK8-1.png?v=1655975658"
                      data-width="62"
                      data-height="31"
                    >
                      bk8-2
                    </option>
                    <option
                      value="562"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/Oppa888.png?v=1655975658"
                      data-width="90"
                      data-height="13"
                    >
                      oppa888
                    </option>
                    <option
                      value="560"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/Vwin.png?v=1655975658"
                      data-width="64"
                      data-height="22"
                    >
                      vwin
                    </option>
                    <option
                      value="558"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/logo-nextbet.png?v=1655975658"
                      data-width="150"
                      data-height="57"
                    >
                      logo-nextbet
                    </option>
                    <option
                      value="234"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/dafabet.png?v=1655975658"
                      data-width="93"
                      data-height="22"
                    >
                      dafabet
                    </option>
                    <option
                      value="229"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/kb.png?v=1655975658"
                      data-width="83"
                      data-height="31"
                    >
                      kb
                    </option>
                    <option
                      value="230"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/jbo.png?v=1655975658"
                      data-width="83"
                      data-height="42"
                    >
                      jbo
                    </option>
                    <option
                      value="226"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/lixi88.png?v=1655975658"
                      data-width="90"
                      data-height="22"
                    >
                      lixi88
                    </option>
                    <option
                      value="233"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/cmd368.png?v=1655975658"
                      data-width="94"
                      data-height="18"
                    >
                      cmd368
                    </option>
                    <option
                      value="227"
                      data-thumb="https://vaobo.com/wp-content/uploads/2021/08/casio.png?v=1655975658"
                      data-width="98"
                      data-height="37"
                    >
                      casio
                    </option>
                  </select>
                </div>
              </div>
            </div>
            <div className="bxaction">
              <input type="submit" name="sbcompare_nhacai" value="So Sánh" />
            </div>
          </form>
        </div>
      </div>
    </article>
  );
}

export default CompareBets;
